Repository ShafinRME/the-delta-news-TS, pull requests merged in 2022-08, with the labels that each got.

#15 Fa/add dashboard 14
  package-lock.json
  package.json
  src/App.tsx
  src/Assets/images/logo/icon.png
  src/Assets/images/service/adv.png
  src/Assets/images/service/liveNews.png
  src/Assets/images/service/updateNews.png
  src/Assets/images/service/why.png
  src/Layout/MainLayout.tsx
  src/components/Share/Header/ActiveLink.tsx
  src/components/Share/Header/Header.tsx
  src/components/Share/Header/MobileNavbar.tsx
  src/components/Share/Header/TodayDate.tsx
  src/components/Share/Header/Weather.tsx
  src/components/Weather/Weather.tsx
  src/data/DashboardData.tsx
  src/data/LiveNewsData.tsx
  src/data/ServicesData.tsx
  src/data/category.tsx
  src/data/faqData.tsx
  src/data/pricingData.tsx
  src/index.tsx
  src/pages/404/Error.tsx
  src/pages/Dashboard/Dashboard.tsx
  src/pages/Dashboard/DashboardComponent/CollapseLink.tsx
  src/pages/Dashboard/DashboardComponent/DashboardCollapseMenu.tsx
  src/pages/Dashboard/DashboardComponent/DashboardNavbar.tsx
  src/pages/Dashboard/DashboardComponent/DashboardSectionTitle.tsx
  src/pages/Dashboard/DashboardComponent/DashboardSidebar.tsx
  src/pages/Dashboard/DashboardComponent/Modal/DeleteModal.tsx
  src/pages/Dashboard/DashboardComponent/Modal/SubmitModal.tsx
  src/pages/Dashboard/DashboardComponent/NewsComponents/ImageScema.tsx
  src/pages/Dashboard/Pages/Admin/Admin.tsx
  src/pages/Dashboard/Pages/AppsDetails/AppsDetails.tsx
  src/pages/Dashboard/Pages/Ecommerce/Ecommerce.tsx
  src/pages/Dashboard/Pages/Moderator/Moderator.css
  src/pages/Dashboard/Pages/Moderator/Moderator.tsx
  src/pages/Dashboard/Pages/News/AddNews.tsx
  src/pages/Dashboard/Pages/News/AllAdminNews.tsx
  src/pages/Dashboard/Pages/News/AllModeratorNews.tsx
  src/pages/Dashboard/Pages/User/User.tsx
  src/pages/Home/Home.tsx
Labels: enhancement

#16 Dn weather and live tv#4
  src/App.tsx
  src/components/Share/Header/Clock.tsx
  src/components/Share/Header/Header.tsx
  src/components/Share/Header/Weather.tsx
  src/components/Weather/Weather.tsx
  src/data/LiveNewsData.tsx
  src/pages/Dashboard/Pages/News/AddNews.tsx
  src/pages/Home/Home.tsx
  src/pages/HomePageNews.tsx
  src/pages/LiveNews/LiveNews.tsx
  src/pages/LiveNews/SingleLiveNews.tsx
Labels: enhancement

#17 #4 weather part
  src/components/Share/Header/Weather.tsx
Labels: enhancement

#20 #5 contact page done
  src/App.tsx
  src/Assets/images/contact/contact-1.png
  src/components/Contact/DesignContact.tsx
  src/components/Contact/InputContact.tsx
  src/components/Contact/MainContact.tsx
  src/pages/contact.tsx
Labels: enhancement

#22 Fa/dt implement search 21
  src/components/Contact/DesignContact.tsx
  src/components/Contact/InputContact.tsx
  src/components/Search/Search.tsx
  src/components/Search/SearchResult.tsx
  src/components/Share/Header/Header.tsx
  src/hooks/allNews.tsx
Labels: enhancement

#25 #5 contact page responsive issue fix
  src/components/Contact/InputContact.tsx
  src/components/Contact/MainContact.tsx
Labels: enhancement

#28 Fa/add voting dahboard 24
  public/_redirects
  src/App.tsx
  src/components/Contact/DesignContact.tsx
  src/components/Search/Search.tsx
  src/data/DashboardData.tsx
  src/pages/Home/Home.tsx
  src/pages/contact.tsx
Labels: enhancement

#31 #23 added advertisement and live tv
  src/App.tsx
  src/Images/service/adv.png
  src/Images/service/liveNews.png
  src/Images/service/updateNews.png
  src/Images/service/why.png
  src/Layout/MainLayout.tsx
  src/components/Advertisement/Services.tsx
  src/components/Advertisement/ServicesItem.tsx
  src/components/Button/Button.tsx
  src/components/ContactSection/ContactSection.tsx
  src/components/FaQ/FaQ.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/HeroData.tsx
  src/components/PriceCard/CardBody.tsx
  src/components/PriceCard/CardButton.tsx
  src/components/PriceCard/CardHeader.tsx
  src/components/PriceCard/PricingPlan.tsx
  src/components/Search/Search.tsx
  src/components/Share/SectionTitle/SectionTitle.tsx
  src/pages/Advertisement.tsx
  src/pages/LiveTv.tsx
Labels: enhancement

#32 Fa/implement authentication 12
  src/App.tsx
  src/components/Share/Header/Header.tsx
  src/components/Share/RequireAuth/RequireAuth.tsx
  src/components/Share/SocialSignIn/SocialSignIn.tsx
  src/components/firebaseConfig.init.tsx
  src/pages/Home.tsx
  src/pages/SignIn/SignIn.tsx
  src/pages/SignUP/SignUp.tsx
  src/pages/SignUp.tsx
  src/pages/Signin.tsx
  src/pages/Sports.tsx
Labels: enhancement

#35 Fa/add news on dashboard 29
  package-lock.json
  package.json
  src/App.tsx
  src/components/Loading/Loadings.css
  src/components/Loading/Loadings.tsx
  src/components/Share/Header/Clock.tsx
  src/components/Share/Header/Header.tsx
  src/components/Weather/Weather.tsx
  src/pages/404/Error.tsx
  src/pages/Dashboard/DashboardComponent/DashboardNavbar.tsx
  src/pages/Dashboard/DashboardComponent/Modal/ModeratorEditModal.tsx
  src/pages/Dashboard/DashboardComponent/Modal/ModeratorViewModal.tsx
  src/pages/Dashboard/DashboardComponent/TableRow/ModeratorRow.tsx
  src/pages/Dashboard/Pages/Ecommerce/Ecommerce.tsx
  src/pages/Dashboard/Pages/Moderator/Moderator.css
  src/pages/Dashboard/Pages/News/AddNews.tsx
  src/pages/Dashboard/Pages/News/AllModeratorNews.tsx
  src/pages/SignIn/SignIn.tsx
  src/pages/SignUP/SignUp.tsx
  src/styles/index.css
  src/utility/Typs.jsx
Labels: enhancement

#36 #12 remove .env local
  .gitignore
  src/components/Share/Header/Header.tsx
  src/components/Share/RequireAuth/RequireAuth.tsx
  src/components/Share/SocialSignIn/SocialSignIn.tsx
  src/config/firebaseConfig.init.tsx
  src/pages/SignIn/SignIn.tsx
  src/pages/SignUP/SignUp.tsx
Labels: enhancement

#37 Fa/add news on dashboard 29
  src/App.tsx
  src/components/Loading/Loading.tsx
  src/components/Loading/Loadings.tsx
  src/components/Loading/SmallLoading.tsx
  src/components/PriceCard/PricingPlan.tsx
  src/components/Share/Header/Header.tsx
  src/components/Share/Header/HeaderData.tsx
  src/components/Share/Header/MobileNavbar.tsx
  src/components/Share/RequireAuth/RequireAuth.tsx
  src/components/Share/RouterLink/RouteLink.tsx
  src/components/Share/SocialSignIn/SocialSignIn.tsx
  src/config/Config.tsx
  src/hooks/Hooks.jsx
  src/hooks/useAdmin.tsx
  src/hooks/useToken.tsx
  src/hooks/useUser.jsx
  src/pages/Dashboard/DashboardComponent/DashboardNavbar.tsx
  src/pages/Dashboard/DashboardComponent/DashboardSidebar.tsx
  src/pages/SignIn/SignIn.tsx
  src/pages/SignUP/SignUp.tsx
Labels: enhancement

#42 Ra/live news and weather part#30
  package-lock.json
  package.json
  src/App.tsx
  src/components/Share/Header/Clock.tsx
  src/components/Weather/Weather.tsx
  src/data/LiveNewsData.tsx
  src/pages/LiveNews/LiveNews.tsx
  src/pages/LiveNews/OneNews.tsx
  src/pages/LiveNews/SingleLiveNews.tsx
Labels: enhancement

#44 Fa/design home page 41
  .env.local
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/components/Share/Header/Header.tsx
  src/components/Share/Pagetitle/PageTitle.tsx
  src/hooks/useNews.tsx
  src/index.tsx
  src/pages/Dashboard/DashboardComponent/DashboardNavbar.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/SingleNews.tsx
  src/styles/index.css
  src/utility/Typs.jsx
  tailwind.config.js
Labels: enhancement

#52 #41 add more section
  package-lock.json
  src/App.tsx
  src/Assets/images/home/adv-1.gif
  src/Assets/images/home/advertisement.png
  src/components/Share/Pagetitle/PageTitle.tsx
  src/pages/Dashboard/Pages/News/AddNews.tsx
  src/pages/Home/Home.tsx
  src/styles/index.css
Labels: enhancement

#49 update weather route #46
  src/App.tsx
  src/components/Weather/Weather.tsx
  src/pages/Currency/Currency.tsx
  src/pages/Currency/types.ts
Labels: enhancement

#60 Fa/user token and save user information 58
  package-lock.json
  package.json
  src/App.tsx
  src/Assets/images/singleAdd/singleBig.jpg
  src/Assets/images/singleAdd/singleBigAdd2.gif
  src/Assets/images/singleAdd/singleSmall.gif
  src/components/Contact/DesignContact.tsx
  src/components/Contact/InputContact.tsx
  src/components/Contact/MainContact.tsx
  src/components/CovidTrack/CountryItem.tsx
  src/components/CovidTrack/GlobalInfo.tsx
  src/components/Share/Header/Header.tsx
  src/components/Share/SocialSignIn/SocialSignIn.tsx
  src/components/Weather/Weather.tsx
  src/data/DashboardData.tsx
  src/data/Users.json
  src/hooks/useToken.tsx
  src/pages/Dashboard/DashboardComponent/Modal/UserDeleteConfirmModal.tsx
  src/pages/Dashboard/DashboardComponent/TableRow/ModeratorRow.tsx
  src/pages/Dashboard/DashboardComponent/TableRow/UserRow.tsx
  src/pages/Dashboard/Pages/News/AllModeratorNews.tsx
  src/pages/Dashboard/Pages/User/AllUsers.tsx
  src/pages/Dashboard/Pages/User/User.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/News.tsx
  src/pages/Home/ShareButton.tsx
  src/pages/Home/SingleNews.tsx
  src/pages/SignIn/SignIn.tsx
  src/pages/SignUP/SignUp.tsx
  src/styles/index.css
  src/utility/Typs.jsx
Labels: enhancement

#62 #58 add more features
  src/App.tsx
  src/pages/Advertisement/Advertisement.tsx
  src/pages/Contact/contact.tsx
  src/pages/Home.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/SingleNews.tsx
  src/pages/HomePageNews.tsx
  src/pages/LiveTV/LiveTv.tsx
  src/pages/Sports.tsx
  src/pages/Sports/Sports.tsx
Labels: enhancement

#66 Ra/video routes implementation#47
  package-lock.json
  src/App.tsx
  src/components/Share/Header/HeaderData.tsx
  src/components/Weather/Weather.tsx
  src/data/VideosData.tsx
  src/pages/Currency/Currency.tsx
  src/pages/Videos/Video.tsx
  src/pages/Videos/Videos.tsx
Labels: enhancement

#70 #63 add video polishing page
  src/Assets/images/videoAdv/small2.gif
  src/Assets/images/videoAdv/video.gif
  src/Assets/images/videoAdv/video2.jpg
  src/Assets/images/videoAdv/videoSmall.gif
  src/components/Weather/Weather.tsx
  src/index.d.ts
  src/pages/Videos/Videos.tsx
  tsconfig.json
Labels: enhancement

#73 Fa/add features home page 72
  package-lock.json
  src/App.tsx
  src/Assets/images/home/homeBigAdds2.gif
  src/Assets/images/home/homeFirstAdds.gif
  src/Assets/images/home/homeFirstSmallgif.gif
  src/components/Contact/InputContact.tsx
  src/components/CovidTrack/Covid19.tsx
  src/pages/Covid.tsx
  src/pages/Currency/HomeCureency.tsx
  src/pages/Home/BangladeshSection.tsx
  src/pages/Home/BusinessSection.tsx
  src/pages/Home/FirstSection.tsx
  src/pages/Home/HealthSection.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/InternationalSection.tsx
  src/pages/Home/SecondSection.tsx
  src/pages/Home/SingleNews.tsx
  src/pages/Home/Voting.tsx
  src/pages/International/International.tsx
  src/styles/index.css
  src/utility/Typs.jsx
Labels: enhancement

#77 Fa/add users featurs 76
  src/components/CategoryNews/CategoryFirstSection.tsx
  src/components/CategoryNews/CategorySecondSection.tsx
  src/components/Share/Header/MobileNavbar.tsx
  src/hooks/useToken.tsx
  src/pages/Currency/HomeCureency.tsx
  src/pages/Dashboard/DashboardComponent/Modal/UserDeleteConfirmModal.tsx
  src/pages/Dashboard/DashboardComponent/TableRow/UserRow.tsx
  src/pages/Dashboard/Pages/User/AllUsers.tsx
  src/pages/Home/SingleNews.tsx
  src/pages/International/International.tsx
  src/pages/SignIn/SignIn.tsx
Labels: bug, enhancement

#78 #76 add features and fix error
  src/Images/service/adv.png
  src/Images/service/liveNews.png
  src/Images/service/updateNews.png
  src/Images/service/why.png
  src/components/Contact/InputContact.tsx
  src/components/Share/Header/TodayDate.tsx
  src/hooks/allNews.tsx
  src/hooks/useNews.tsx
  src/hooks/useToken.tsx
  src/pages/Advertisement/Advertisement.tsx
  src/pages/Books/Books.tsx
  src/pages/Dashboard/DashboardComponent/Modal/ModeratorEditModal.tsx
  src/pages/Dashboard/DashboardComponent/Modal/ModeratorViewModal.tsx
  src/pages/Dashboard/DashboardComponent/Modal/UserDeleteConfirmModal.tsx
  src/pages/Dashboard/Pages/News/AddNews.tsx
  src/pages/Dashboard/Pages/News/AllModeratorNews.tsx
  src/pages/Dashboard/Pages/User/AllUsers.tsx
  src/pages/Health/Health.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/News.tsx
  src/pages/Home/SingleNews.tsx
  src/pages/Home/Voting.tsx
  src/pages/LiveTV/LiveTv.tsx
  src/pages/LiveTv/LiveTv.tsx
  src/utility/Urls.tsx
Labels: bug, enhancement

#79 #76 fix error
  src/App.tsx
  src/pages/LiveTV/LiveTvs.tsx
  src/pages/LiveTv/LiveTv.tsx
Labels: bug, enhancement

#80 #76 fix footer error
  src/App.tsx
  src/components/Share/Footer/FooterData.tsx
  src/pages/Dashboard/Pages/User/AllUsers.tsx
  src/pages/Tv/LiveTvs.tsx
Labels: bug, duplicate, enhancement
